name: Build and Test with Maven

on:
  push:
    branches: [ main ]  # Runs when pushing to the main branch
  pull_request:
    branches: [ main ]  # Runs on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu to run the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Step 1: Checkout your code from GitHub

    - name: Set up JDK
      uses: actions/setup-java@v4  # Step 2: Set up Java (Temurin)
      with:
        distribution: 'temurin'
        java-version: '17'  # Use Java 17 or whatever version you need

    - name: Build with Maven
      run: mvn clean install -DskipTests  # Step 3: Build the code and skip tests for now

    - name: Run unit tests
      run: mvn test  # Step 4: Run unit tests

    - name: Run integration tests
      run: mvn failsafe:integration-test failsafe:verify  # Step 5: Run integration tests using Failsafe

    - name: Package application (JAR)
      run: mvn package  # Step 6: Package your application into a JAR file

    - name: Archive JAR file
      uses: actions/upload-artifact@v4  # Step 7: Upload the JAR file as an artifact
      with:
        name: my-jar
        path: target/*.jar  # Adjust path if necessary
